### ISSUE TITLE
UI: Expired mosaics, hide by default?

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#100]
We are showing expired mosaics together with non-expired in the dashboard, and in the transfer dropdowns.

I think that they should not be visible in the dashboard and in the transaction forms

I think they should be visible in the mosaic list only if a "show expired" button is clicked #

**Comment by decentraliser** [comment]
make sure you do it on my branch

**Comment by NemTechCN** [comment]
fixed
