### ISSUE TITLE
Refactoring: Market data

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#106]
Market data methods should be pulled out from the components and necessary data should be dispatched through the store:

- [ ]  Most of them should be loaded on app init, after other wallet-related information fetching is done

- [ ]  No unnecessary refresh

- [ ]  Will permit to dispatch data such as XEM/USD price in a nicer way

- [x] **All errors should be caught, and nothing should be blocking**

**Comment by NemTechCN** [comment]
Will upgrade remote server in a few days .

**Comment by domakun** [comment]
No network interface available at this time, need to wait for the response from the foundation
