### ISSUE TITLE
Change Password page needs English cleaned up

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#110]
![image](https://user-images.githubusercontent.com/10395907/64838766-4df44c00-d5ba-11e9-97e1-9a88194decc6.png)

Lock password -> Change password
My FIRst Pa$$word -> Current password
9_pass-WORD -> New password
hint -> Hint
PLACEHOLDER_cipher_hing -> Enter hint

**Comment by decentraliser** [comment]
fixed in #113
