### ISSUE TITLE
UI: network list improvement

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#148]
![image](https://user-images.githubusercontent.com/45383558/65317646-d08a9600-dbce-11e9-8b58-10c660aca903.png)

**Comment by NemTechCN** [comment]
Need fix node change bug

**Comment by decentraliser** [comment]
also, the active node doesn't appear as selected

![image](https://user-images.githubusercontent.com/36499647/65401629-22fcca00-ddfc-11e9-9c89-f17c1a9e5d98.png)

**Comment by decentraliser** [comment]
index.ts / nodeConfig is a duplicate of config/view/node.ts, please delete one of them

**Comment by NemTechCN** [comment]
fixed
