### ISSUE TITLE
UI:use address in account list 

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#150]
![244178836222878099](https://user-images.githubusercontent.com/45383558/65317884-39720e00-dbcf-11e9-93c9-a17dea1bb02f.jpg)
reaplace address by SAUA5***OYLKF (self)

**Comment by jabo38** [comment]
I would also mention, if there are no multisig accounts associated with this account, there shouldn't be a dropdown menu at all. It should just show from and show the account's address.

**Comment by decentraliser** [comment]
closed in favour of #101
