### ISSUE TITLE
Set a default network. 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#156]
After this wallet launches, most people will want to use the main net, so this should automatically have "main net" pre-chosen. Of course a person can still select a new network from the dropdown, but we should have already chosen main net for them. For the testnets, right now Mijin_Test should be the default network.

**Comment by jabo38** [comment]
![image](https://user-images.githubusercontent.com/10395907/65394390-1e300b80-dd53-11e9-95df-90be30479fcd.png)

**Comment by decentraliser** [comment]
closed in favour of #3
