### ISSUE TITLE
If I am confirming a passphrase I can hit the same word more than once and no way to undo. 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#159]
When I confirm a passphrase, if I make a mistake or hit the same word more than once, there is no way to erase that word. Typically a person could hit backspace on the keyboard and it would erase the latest entry. Or there would be a delete button in UX somewhere. In this case hitting previous actual doesn't erase the last word but instead takes me to the previous screen. 

![image](https://user-images.githubusercontent.com/10395907/65394463-2ccaf280-dd54-11e9-989a-f45e5487de64.png)

**Comment by decentraliser** [comment]
Was it bbq time?

You can actually undo by clicking on one "rib" in the box

However you shouldn't have been able to bring more ribs in the first place, also I would like the words to change colours when they have been selected to remove some mental overhead

**Comment by decentraliser** [comment]
fixed

**Comment by decentraliser** [comment]
continued in #179
