### ISSUE TITLE
UI: Fees review

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#164]
Up for discussion but doesn't it seem better to suggest the fee and let that non-adjustable for users?

**Comment by jabo38** [comment]
![image](https://user-images.githubusercontent.com/10395907/65394933-37d45180-dd59-11e9-87f2-8f7657f84022.png)

**Comment by decentraliser** [comment]
let's take a decision, launched a thread in the slack.

I suggest a standard component to be used in all forms, with 3 buttons:

Fast | Normal | Slow

We can put arbitrary data in there and adjust while having usage feedback

**Comment by decentraliser** [comment]
![image](https://user-images.githubusercontent.com/36499647/65401085-7240fb80-ddf8-11e9-8e08-fc4df1d0f46f.png)

**Comment by decentraliser** [comment]
All fields in one line?
![image](https://user-images.githubusercontent.com/36499647/65401531-4f641680-ddfb-11e9-8e75-fee1e9181695.png)
