### ISSUE TITLE
Need delegated harvesting key auto-filled

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#166]
There should be a way of using BIP44 to created a new derivation path so that the delegated private key is automatically generated. This should be discussed. But the point is, if somebody knows their regular account's private key, the delegated key should be created deterministically. That way delegated keys can also be known/recreated across different apps easily. 

![image](https://user-images.githubusercontent.com/10395907/65395663-a28a8a80-dd63-11e9-855c-827b530bda1c.png)

**Comment by decentraliser** [comment]
We are not sure about what to do here, I propose to discuss it during next meeting

**Comment by NemTechCN** [comment]
fixed
