### ISSUE TITLE
UI: update UI stylesheet

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#171]
1.![image](https://user-images.githubusercontent.com/45383558/65397722-030ddc00-dde5-11e9-96c5-c084a1aba374.png)
2.![image](https://user-images.githubusercontent.com/45383558/65397734-191b9c80-dde5-11e9-8f6c-b33b498bfaaf.png)
3.Harvester please show the last 4 letters
4.Select the address, the middle abbreviation, the mark is displayed at the back; Chinese should not be translated as "public key" and changed to "sender".
5.
![image](https://user-images.githubusercontent.com/45383558/65397764-5122df80-dde5-11e9-82f1-88fc0c09ae03.png)

**Comment by decentraliser** [comment]
In the transaction list, the left and right icons are not aligned, and I think that the div height should be reduced by 5 - 10px
![image](https://user-images.githubusercontent.com/36499647/65400325-196f6400-ddf4-11e9-902e-0cd645e8ec33.png)

**Comment by NemTechCN** [comment]
fixed
