### ISSUE TITLE
Namespace list 

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#176]
1.List enable filter and paging
2.Create sub-namespaces and namespace merges
3.The div that spawn when clicking on ... doesn't stick to the button
![image](https://user-images.githubusercontent.com/36499647/65399486-74eb2300-ddef-11e9-9092-8d6e73b32bcd.png)

**Comment by decentraliser** [comment]
I think expired namespaces should be hidden by default

**Comment by NemTechCN** [comment]
![image](https://user-images.githubusercontent.com/45383558/65585148-93e6e200-dfb4-11e9-8ded-5222a9bf2914.png)

**Comment by NemTechCN** [comment]
fixed
