### ISSUE TITLE
Transfer mosaic list improvement

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#182]
If mosaic aliased then show alias
Forbid duplicates

![image](https://user-images.githubusercontent.com/36499647/65401594-d4e7c680-ddfb-11e9-9a10-e9c04c98d0b3.png)

**Comment by NemTechCN** [comment]
![image](https://user-images.githubusercontent.com/45383558/65417167-01b3d200-de2c-11e9-8e96-52c142343b8a.png)

**Comment by NemTechCN** [comment]
fixed
