### ISSUE TITLE
UI: Wallet list (wallet management)

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#187]
Always keep the wallets in the same order
The order of the wallets should be their creation date, from newest to oldest

First account and its "children": orange
Imported accounts: black
Active account: big and blue (Doesn’t move to top)

**Comment by NemTechCN** [comment]
fixed

**Comment by jabo38** [comment]
the date is better from oldest to newest, so oldest is on top and newest is on the bottom. that almost always how other apps handle it.
