### ISSUE TITLE
UI:wallet list overflow bug

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#188]
![631602472355415780](https://user-images.githubusercontent.com/45383558/65406743-0c15a200-de13-11e9-9879-be5c7f28eea3.png)
better to fix wallet color in list

**Comment by NemTechCN** [comment]
Wallet installation creates time row, new one is placed behind

**Comment by NemTechCN** [comment]
Inactive with a color, active with a color, size becomes, position does not change, UI assists

**Comment by decentraliser** [comment]
closed in favour of #187
