### ISSUE TITLE
account ordering 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#219]
1. The accounts listed in the wallet management page are listed where oldest is on bottom and newest is on top. It is nice that they are static and that is an improvement but ordering usually in most apps have the oldest at the top and newest at the bottom. 

2. The shortcut menu in the top right corner of the wallet has it's ordering of wallets changing. It should be static and match the list in the wallet management page. 

![image](https://user-images.githubusercontent.com/10395907/65712018-bbdd5080-e05b-11e9-91b4-9b3c0373a272.png)

![image](https://user-images.githubusercontent.com/10395907/65712052-d0b9e400-e05b-11e9-84f8-517ef8ff7e49.png)

**Comment by NemTechCN** [comment]
fixed
