### ISSUE TITLE
Need a way for Trezor/Ledger log in on start screen. 

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#221]
![image](https://user-images.githubusercontent.com/10395907/65721748-4334bf00-e070-11e9-83ed-d94afd9a4936.png)

**Comment by decentraliser** [comment]
This would be a change to the current system, where the ledger wallet is treated as an imported wallet (such as wallet imported from private key)

We can discuss it during the meeting

**Comment by domakun** [comment]
we have added it in login page
