### ISSUE TITLE
Add refresh button / icon to any listing component

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#252]
**Expected Behaviour**

It should be possible to **refresh** the data that is displayed by clicking a refresh icon button.

**Actual Behaviour**

Currently data request/fetch is done on time of display of component, it is necessary to also make it possible to *refresh* the displayed data manually.

**Comment by decentraliser** [comment]
Refresh is not done on time of display of component anymore. It is done on wallet / node change, and data is updated when transactions are (un)confirmed. 

But yes, a refresh button can be nice to have
