### ISSUE TITLE
Arrow representing txs can be more clearly defined

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#253]
![image](https://user-images.githubusercontent.com/10395907/65838888-5bede080-e2cd-11e9-9e5c-5a2730169249.png)

Usually an up arrow means tx out, a down arrow means tx in, and a sideways arrow means not in or out. So something like namespace, alias, or multisig can be sideways.

**Comment by decentraliser** [comment]
OK for up and down, (in a local branch it's left right, orange and green, can change orientation)

However I'm not sure about the not deposit or withdrawal as we affect different icons to different transaction types
