### ISSUE TITLE
Balances on Account Page are updating but not frequently

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#254]
Most of these accounts have had txs out and when I go to the Dashboard, I can see a different balance (and correct balance) shown in the Dashboard, but when I go to the Wallet page I see the old balance (and wrong balance)

![image](https://user-images.githubusercontent.com/10395907/65839107-dc154580-e2cf-11e9-8723-d63ae66eb8f8.png)

**Comment by evias** [comment]
when addressing this, please have a look at #252 as well.

**Comment by decentraliser** [comment]
pushed a fix:

- All wallets balances get refreshed when starting the app
- A wallet balance is refreshed when switching to it
- The active wallet's balance is always up-to-date

If a non-selected wallet's balance changes after the user logs in, and the user never selects this wallet during the session, it's balance won't be updated.

I prefer to do that later after some cleanup is done
