### ISSUE TITLE
Dashboard: Display account info instead of chart?

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#258]
![image](https://user-images.githubusercontent.com/36499647/65841658-5ccb5480-e357-11e9-8660-55e29f82a6dc.png)

**Comment by decentraliser** [comment]
![image](https://user-images.githubusercontent.com/36499647/66298975-37c17d80-e925-11e9-8196-3b9d55ec7198.png)

**Comment by evias** [comment]
I think it would actually be best if this chart was using `blockchain data` instead of price data.

For instance, it could be a chart of the number of transactions in last blocks, or similar.

**Comment by decentraliser** [comment]
I'ld really like to increase the height of the transaction list section by about 50-60pix, to add 2 visible lines

Also I think we must show the user if he has tx awaiting for cosign in this screen (or in the top menu, eg. with a notification bell)

**Comment by decentraliser** [comment]
We could have a reminder section that could for example show namespaces that are close to expiration / in the grace period
