### ISSUE TITLE
Delete wallet bugs

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#270]
Password error in all cases when trying to delete the main wallet and its children
and variable in the text
Text way too long (150char max)

![image](https://user-images.githubusercontent.com/36499647/65853778-36c0a700-e38d-11e9-8c36-1c323c6d3947.png)

**Comment by decentraliser** [comment]
> * Password error in all cases when trying to delete main wallet and its childs
> * and variable in the text
> * Text way too long (150char max)

**Comment by NemTechCN** [comment]
fixed
