### ISSUE TITLE
UI: update alias dialog

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#273]
after #295 is merged

There is now only one alias dialog, please style it for all possibilities

BIND ADDRESS
![image](https://user-images.githubusercontent.com/36499647/66252868-28122f80-e793-11e9-92e9-918afeaf5521.png)

after #295 merge

UNBIND ADDRESS
![image](https://user-images.githubusercontent.com/36499647/66252858-1d579a80-e793-11e9-9707-00fad355d4e7.png)

BIND FROM NAMESPACES
![image](https://user-images.githubusercontent.com/36499647/66252886-4710c180-e793-11e9-9f1a-d97f5b073445.png)

UNBIND FROM NAMESPACES
![image](https://user-images.githubusercontent.com/36499647/66252878-3b24ff80-e793-11e9-9545-7e21adc4dd05.png)

BIND FROM MOSAICS
![image](https://user-images.githubusercontent.com/36499647/66252899-614a9f80-e793-11e9-9d4c-683f9393a0a5.png)

UNBIND FROM MOSAICS
![image](https://user-images.githubusercontent.com/36499647/66252892-57c13780-e793-11e9-9f32-cff7b7c5ac86.png)

**Comment by decentraliser** [comment]
Please review it after #295 is merged
