### ISSUE TITLE
Remote harvesting improvements

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#289]
- [x] Review wording (how to get a profit...)
- [x] Make div scrollable
- [x] Add transaction form
- [x] Set an account's remote public key at store level
- ====> in `App.js mounted() hook`
- ====> in `App.js On Wallet Change`
- ====> add trigger in `store/plugins/onTransactionRefresh`

![image](https://user-images.githubusercontent.com/36499647/66184242-13a83700-e6ae-11e9-893d-5ce43fbd836c.png)

**Comment by NemTechCN** [comment]
fixed
