### ISSUE TITLE
Password input error with special characters

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#31]
Using following password, i receive an error: `+K"ZinrsBXx=X~H$Wy9qeo$%&~wvViXB` when trying to *Import a wallet* by private key.

Following is a screenshot of the error display:

![Screenshot 2019-08-23 at 8 41 41 AM](https://user-images.githubusercontent.com/141805/63571902-dcf4e200-c581-11e9-9b1b-337d23b80274.png)

**Comment by decentraliser** [comment]
that was actually the expected behaviour, I'll add more special characters

**Comment by decentraliser** [comment]
/~7ja/5>b3Q+cA68APi6SJR[_t.nbxY&

**Comment by evias** [comment]
this second password is a different problem. I believe end-users should be able to input anything as the password, the regular expression for validation here should not be limiting on size nor on content - what it can do is to give guidelines (minimum 1 upper case, minimum 1 number, etc.).

**Comment by decentraliser** [comment]
OK, I'ld prefer to have the passwords free, keeping min 8 char (SDK
Password constructor requirement), I could just remove the regex

**Comment by evias** [comment]
yes minimum 8 characters is fine
