### ISSUE TITLE
catch all charts error

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#310]
uncaught errors related to market data can cause fuzzy behaviour

eg:

![image](https://user-images.githubusercontent.com/36499647/66284694-9a9e1f00-e8fb-11e9-9115-872e45ade774.png)

**Comment by NemTechCN** [comment]
fixed

**Comment by decentraliser** [comment]
![image](https://user-images.githubusercontent.com/36499647/67455665-e8878680-f660-11e9-92b1-e7fc548b86bd.png)

**Comment by decentraliser** [comment]
the following error is blocking the app when the app can not reach the remote server 


`Error in mounted hook (Promise/async): "TypeError: Failed to fetch"`
