### ISSUE TITLE
UI: chart tooltip overflowing on tx detail modal

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#313]
![image](https://user-images.githubusercontent.com/36499647/66302029-cab0e680-e92a-11e9-9602-582cf5aa1704.png)

**Comment by NemTechCN** [comment]
How is it triggered?

**Comment by decentraliser** [comment]
Pass the mouse on the chart so the tooltip shows, then click to n a transaction

A good fix would be to kill the tooltip onMouseOut

**Comment by NemTechCN** [comment]
fixed
