### ISSUE TITLE
mosaicInfo undefined bug

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#317]
need to fix it in transaction list
![image](https://user-images.githubusercontent.com/45383558/66366423-ee277000-e9c2-11e9-9522-4c6174783dd9.png)

**Comment by decentraliser** [comment]
how to reproduce it? I don't have this bug

**Comment by NemTechCN** [comment]
> how to reproduce it? I don't have this bug

My fault ，it's not shown at master
