### ISSUE TITLE
Transaction detail modal: mosaics should be shown in a table

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#327]
As this component is used for transaction confirmations, all the mosaics included in the transactions should be displayed very clearly

one solution would be to display them in a dedicated component that would take mosaics as a prop

![image](https://user-images.githubusercontent.com/36499647/66448280-9bfa5380-ea83-11e9-802f-2afb93d42761.png)

**Comment by NemTechCN** [comment]
fixed
