### ISSUE TITLE
Reduce the frequency of sdk , adjust the mode of sdk call

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#329]
Try to extract functions that use the same sdk method, reduce the frequency of sdk in the code, and reduce the work that needs to be done after sdk upgrade.

**Comment by evias** [comment]
Please elaborate what is intended with this issue.

**Comment by NemTechCN** [comment]
> Please elaborate what is intended with this issue.

sorry for my not detailed introduction , I think we should integrate sdk functions to reduce the work done by sdk upgrades .
