### ISSUE TITLE
update AppWallet.checkPassword

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#358]
update AppWallet.checkPassword to take a string so it can handle errors

**Comment by NemTechCN** [comment]
Do you mean we need update the return to be a string instead of a boolean ? But the verification result is only true or false, so I don't think I understand what you mean.
![image](https://user-images.githubusercontent.com/45383558/67350005-18109300-f57c-11e9-8c91-bd2e3a21f80f.png)

**Comment by decentraliser** [comment]
It's about the function parameter

It should be password: string, not password: Password
