### ISSUE TITLE
No error if a person enters CAPITAL letters

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#371]
![image](https://user-images.githubusercontent.com/10395907/66690220-3e693100-ec54-11e9-8e42-2b04abded74d.png)

**Comment by decentraliser** [comment]
it does throw an error when you click create
real-time validation on input will be implemented in the future

![image](https://user-images.githubusercontent.com/36499647/66692459-1bc92d80-ecd1-11e9-900d-9d1d5e72fc28.png)
