### ISSUE TITLE
Change delegated harvesting link/unlink UI element

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#38]
![image](https://user-images.githubusercontent.com/36499647/63696054-7c4cfa00-c84c-11e9-9d9f-64d3ba000601.png)

Here we have a switch that toggles a form, this is an antipattern, especially since the switch will turn on or off onClick whatever happens

For example, it would be better to have a single button with a link or unlink label depending on the current state

**Comment by NemTechCN** [comment]
fixed
