### ISSUE TITLE
Confirmation counter bug

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#415]
![image](https://user-images.githubusercontent.com/36499647/66813223-f9504200-ef66-11e9-9556-5a3b4b65ec88.png)

(I don't know how to reproduce it)

**Comment by NemTechCN** [comment]
it is not a bug
![image](https://user-images.githubusercontent.com/45383558/66816806-459e8080-ef6d-11e9-97ec-3370b329f876.png)
