### ISSUE TITLE
Fee selector: show the fee unit price in the Select

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#422]
Show the unit fee in the Select, and the total underneath

Eg. Sending an aggregate tx involves 1 aggregate fee and one inner fee. 
Choice from the select: normal: 1XEM
Showing under the select: Total Max fee: 2XEM

**Comment by NemTechCN** [comment]
How about make a list of fees ？ Under normal circumstances, this list is hidden. When the user clicks on the fee details, the fee list is displayed as a pop-up window. Like this :
![image](https://user-images.githubusercontent.com/45383558/67350342-14314080-f57d-11e9-936e-a55749d50881.png)

**Comment by decentraliser** [comment]
We can think about that after checkPWdialog is refactored. Refactoring will be done by Labris.

Next step is #340  merge

**Comment by domakun** [comment]
we have updated confirme dialog
