### ISSUE TITLE
Windows build, do not allow opening another instance of the wallet

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#458]
![image](https://user-images.githubusercontent.com/36499647/67073775-63145a00-f1ba-11e9-8a10-de78e7f41941.png)

When clicking here, it throws the error below.
If you click ok on the error, it kills the app, or it opens the error window one more time

![image](https://user-images.githubusercontent.com/36499647/71223075-b2d3e680-230d-11ea-8eba-5503d4f12f79.png)

**Comment by decentraliser** [comment]
why on hold @NemTechCN ?

There might be the fix:
[https://stackoverflow.com/questions/35916158/how-to-prevent-multiple-instances-in-electron](https://stackoverflow.com/questions/35916158/how-to-prevent-multiple-instances-in-electron)

**Comment by domakun** [comment]
fixed in build file

**Comment by domakun** [comment]
[main.txt](https://github.com/nemfoundation/nem2-desktop-wallet/files/3971104/main.txt)

**Comment by decentraliser** [comment]
reopening this one, updated the description

**Comment by domakun** [comment]
> reopening this one, updated the description

[main.txt](https://github.com/nemfoundation/nem2-desktop-wallet/files/4001139/main.txt)
this file really fix the issue
