### ISSUE TITLE
Complete unit test

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#527]
**1. transfer transaction**
- [x]  should create a normal transfer transaction object while did not choose multisig public key；
- [x]  should create an aggregate complete transaction object while choose 1-of-1 multisig；
- [x]  should create an aggregate bonded transaction object while choose 2-of-2 multisig；
- [x]  should not create any transaction object while recipient is neither address nor alias；
- [x]  should create a transaction object while recipient is an alias；
- [x]  should not create a transaction object while mosaic list is null；
- [x]  should sort mosaics while add new mosaic；
- [x]  should create a transaction object while message is null；
- [x]  should not create a transaction object while message length > 1023；
- [x]  should not create a transaction object while networkType are not match(sender , receiver , 
node)；

**2. mosaic transaction**
- [x] should create a normal aggregate transaction while all param is right ; 
- [x]  should create an aggregate complete transaction while  choose 1-of-1 multisig ;
- [x]  should create an aggregate bonded transaction while  choose 2-of-2 multisig ;
- [x]  should not create a transaction while divisibility < 0 ;
- [x]  should not create a transaction while  divisibility > 6 ;
- [x]  should not create a transaction while absolute supply <= 0 ;
- [x]  should not create a transaction while absolute supply > 9,000,000,000,000,000 ;

**3. namespace**
- [x] should create a NamespaceRegistrationTransaction while all param is right ;
- [x] should create an aggregate complete transaction while account is a 1-of-1 multisig;
- [x] should create an aggregate bonded transaction while account is a 2-of-2 multisig;
- [x] should not create a normal namespace create transaction while rootNamespaceName is substandard;
- [x] should not create a normal namespace create transaction while duration is less than 4;
- [x] should not create a normal namespace create transaction while duration is more than 2102400;
- [x] should not create a normal namespace transaction while namespace name is invalid

**4.sub-namespace**
- [x] should create a NamespaceRegistrationTransaction while all param is right 
- [x] should not create a NamespaceRegistrationTransaction while sub namespace is invalid 
- [x] should create an aggregate complete transaction while account is a 1-of-1 multisig
- [x] should create an aggregate bonded transaction while account is a 2-of-2 multisig
- [x] should not create a namespace transaction while the length of sub namespace name is longer than 64
- [x] should create a namespace transaction while the length of sub namespace name is 64

**5.multisig**

**others**
- [ ] should not create seed wallet while the amount of seed wallet is 10 ; 
- [x] DisabledForms should not exists while default mosaic has already set ；
- [x] DisabledForms should exists while default mosaic is not set ；
- [x] DisabledForms should exists while activeAccount is a multisig ；

**Comment by decentraliser** [comment]
Can close this one I think

Maybe you can do the last unchecked one in the login PR? ( should not create seed wallet while the amount of seed wallet is 10)
