### ISSUE TITLE
Fix transfer transaction validate bug

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#530]
- [x] 1.need to limit the length of the transfer transaction message to 1024(max is 1023);

- [x] 2.update detail modal stylesheet;

- [ ] 3.Prevent transactions from being sent in network types that do not match (networkType in senderAccount, receiverAccount and node)

![image](https://user-images.githubusercontent.com/45383558/67760113-a8b70980-fa7b-11e9-8e22-8618a0705ae3.png)

- [x] 4. asset name and asset amount
goal：don't throw error while ① is null ;
status quo：throw error while ① is null.

image
![image](https://user-images.githubusercontent.com/45383558/67824662-00985380-fb02-11e9-8e34-5c5e51b40377.png)

**Comment by decentraliser** [comment]
let me 2 and 3

**Comment by NemTechCN** [comment]
> let me 2 and 3

let me  fix 1

**Comment by decentraliser** [comment]
i meant  and 3, just wants to make sure vee-validate is used

**Comment by NemTechCN** [comment]
goal：don't throw error while ① is null and ② is not null ; 
status quo：throw error while ① is null and ② is not null

![image](https://user-images.githubusercontent.com/45383558/67822517-98df0a00-fafb-11e9-9c94-cae92389e044.png)
