### ISSUE TITLE
UI: TransactionSumarry: Show inner transactions details in tabs

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#544]
Instead of opening a new popup to show inner transactions, do a tab system

![image](https://user-images.githubusercontent.com/36499647/67874209-93230c00-fb6f-11e9-891a-e4bfdb518ff7.png)

**Comment by NemTechCN** [comment]
https://www.iviewui.com/components/collapse
Can refer to this

**Comment by decentraliser** [comment]
That would be awesome!
