### ISSUE TITLE
Remote harvesting bugs and improvements

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#625]
- Put automatically the port number (:3000) when it is not provided
- nothing_was_found_at_this_address i18n key
- List the harvesting request near the action buttons

**Comment by NemTechCN** [comment]
how about use hd wallet to generate remote accounr

**Comment by decentraliser** [comment]
that's what we are doing
https://github.com/nemfoundation/nem2-desktop-wallet/issues/626

**Comment by decentraliser** [comment]
closed in favour of #626 and #637
