### ISSUE TITLE
Update lineChart 

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#63]
![165429997918502485](https://user-images.githubusercontent.com/45383558/64106140-2e834500-cdaa-11e9-913a-bd7364ceeedc.jpg)

**Comment by NemTechCN** [comment]
![901302992929597448](https://user-images.githubusercontent.com/45383558/64106156-3511bc80-cdaa-11e9-9570-84787f7a1cca.jpg)

**Comment by decentraliser** [comment]
Just to precise, I'm not sure about having a third axis on the right, because it might be tricky to make.

However, I think we should definitely have the BTC price in the curve tooltip, otherwise, it is confusing

**Comment by decentraliser** [comment]
also, this number is unclear, and not useful IMO
![image](https://user-images.githubusercontent.com/36499647/64159123-415e4e00-ce6c-11e9-8aa8-577f36937fd8.png).

Useful percentages would be 1-day and 1-week variations and could be displayed outside of the chart. (near the total market cap maybe).
Having %variation vs BTC AND wallet base currency would be really cool

Removing this percentage from the tooltip would make space for putting the BTC price in it (so there would be no custom modification to make to the chart).
The XEM price could be in green, and BTC price in orange (same colour as the curves)

**Comment by NemTechCN** [comment]
fixed
