### ISSUE TITLE
 enter aliases manually

### ISSUE THREAD

**Issue by NemTechCN** [nemfoundation/nem2-desktop-wallet#66]
enter aliases manually
![759214794040675748](https://user-images.githubusercontent.com/45383558/64108308-0c3ff600-cdaf-11e9-8db7-a20ee4fa90ca.jpg)

**Comment by evias** [comment]
also, would like to note there is a bug about the above dropdown.

**It only displays namespaces that you own** but should also permit to request the network for an existing address alias linked to the namespace input.

**Comment by NemTechCN** [comment]
fixed
