### ISSUE TITLE
UI: review for Account Creation/Import

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#667]
Several review issues poppep up while testing the wallet in terms of **user interface** and user experience.

**Actionable Items**:

- Generate new account page's last screen should have a `Back` button as displayed in Screenshot 1
- Generate new account page "Verify backup mnemonics" : Button Previous and Next must match the design of the previous page. (Gray button for **Back** and green button **Next**). Please use consistent design for these all across the app. (new component ?).
- Improvements needed with mnemonic input field: Should encapsulate words in grey box as well as add validation of words as being part of the dictionary.
- Import an old account page "Create an account and password": The submit button here should say **Restore Mnemonic**.
- Import an old account page "Input mnemonic": The submit button here should say **Import Mnemonic**.
- Import an old account page "Address to Interact With": The **CATAPULT** and **TEST_NET** information is not actionable, should be removed. The title of the page can instead say: **Addresses will interact with the Catapult Testnet** and "Testnet" can be different depending on the connected network.

**Screenshots**:

![Screenshot 1](https://user-images.githubusercontent.com/141805/69957102-2b5f3880-1502-11ea-913f-300f412e57af.png)

**Comment by dgarcia360** [comment]
Another suggestion: Rename "Import an old account" to "Import an existent account".

**Comment by dgarcia360** [comment]
![image](https://user-images.githubusercontent.com/9107969/70315866-61f2c700-1812-11ea-86e4-08b7a53be850.png)

"confirm password" should start with an uppercase letter.
