### ISSUE TITLE
UI: node switch button link fix

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#673]
**Expected behaviour**

When I click the TEST_NET part of the node switch button, it should open the dropdown.

**Actual behaviour**

It is currently only possible to open the dropdown when I click the green dot. It should also work when I click the text.

**Screenshots**

<img alt="Screenshot 1" src="https://user-images.githubusercontent.com/141805/69960135-091ce900-1509-11ea-919a-b8fa749c5dfe.png" height="400" />

**Comment by domakun** [comment]
fixed in build file
