### ISSUE TITLE
UI: namespace list

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#68]
Here I would expect to see if a namespace is linked to something, and if yes, to what (maybe with detail on click or on hover)

Also, it might be nice to be able to link/unlink from this view

![image](https://user-images.githubusercontent.com/36499647/64109274-ab65ed00-cdb1-11e9-8aa6-715682223b04.png)

**Comment by NemTechCN** [comment]
fixed
![image](https://user-images.githubusercontent.com/45383558/64321471-2cf88d80-cff3-11e9-87dc-25176c7aa250.png)
