### ISSUE TITLE
UI: delete wallet

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#70]
I think it would be better to have the wallet name here, and maybe its address also

note that i18n offers the possibility to inject variables into translated content, so something like that would be feasible:

you are about to delete the wallet `{ wallet.name }  `, ...

![image](https://user-images.githubusercontent.com/36499647/64137373-6af68580-ce2a-11e9-9fa6-3b6844ae6078.png)

**Comment by NemTechCN** [comment]
fixed
