### ISSUE TITLE
Refactor @Watch events

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#71]
There are some common events when store values have to be updated, for example:

- Wallet Change
- Node Change
- Network Change
- Transaction confirmed

Now, these changes are listened to in components, with the `@watch` method. The same event is sometimes listened to in multiple places, for firing the same update method

Solution:
Refactor these methods in one single (eg. `app.vue`), and use one of the two last methods [presented here: ](https://dev.to/viniciuskneves/watch-for-vuex-state-changes-2mgj)

**Comment by evias** [comment]
should be using shared `this.$store.watch` and `this.$store.subscribe`.

Not sure I understood the part where it should be one single file, can you elaborate @decentraliser ?
