### ISSUE TITLE
do not use v-html

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#713]
in `Information.vue`

once it is done, please uncomment the v-html rule in `.eslintrc`:

**Comment by dl-nice** [comment]
why do not use v-html?

**Comment by decentraliser** [comment]
to prevent XSS attacks

**Comment by dl-nice** [comment]
If you don't use v-html, how to complete the content rendering of rss <content: encode> and use regular to extract the data in various tags?

**Comment by decentraliser** [comment]
Check the comments I put on slack

https://nem2.slack.com/archives/CME5PV744/p1576487455019200

**Comment by dl-nice** [comment]
Then use rich text parsing

**Comment by dl-nice** [comment]
Use only HTML interpolation for trusted content, never user-provided content. In this case, it is safe

**Comment by dl-nice** [comment]
At first I wanted to use a <div> tag to interpolate text, that is, <div> {{str}} </ div>. As a result, it can be imagined that the newline character in str-\ n is displayed as a space, and the addition of <br> is directly displayed as a string! !! !!

After some searching on Google, I finally found a more elegant way to solve the above problem. That is, the text difference is still used, but the <div> tag is replaced with the <pre> tag.

**Comment by dl-nice** [comment]
At first I wanted to use a <div> tag to interpolate text, that is, <div> {{str}} </ div>. As a result, it can be imagined that the newline character in str-\ n is displayed as a space, and the addition of <br> is directly displayed as a string! !! !!
After some searching on Google, I finally found a more elegant way to solve the above problem. That is, the text difference is still used, but the <div> tag is replaced with the <pre> tag.

**Comment by decentraliser** [comment]
OK, please make sure to validate with @evias when you have a solution

**Comment by dl-nice** [comment]
https://github.com/nemfoundation/nem2-desktop-wallet/pull/759
