### ISSUE TITLE
have to enter IP address perfectly

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#734]
I can only get node info if I enter 

`http://api-harvest-20.ap-southeast-1.nemtech.network:3000`

Would be nice if I could just enter

`api-harvest-20.ap-southeast-1.nemtech.network`

![image](https://user-images.githubusercontent.com/10395907/71023974-355e7980-2147-11ea-93a2-5d9ac3ac7f0a.png)

The nicest though is having a node auto-suggested though as discussed in the call, and if somebody doesn't like the auto-suggested node, then they can click through to add their own in a more advanced screen.

**Comment by decentraliser** [comment]
closed in favour of #637

Autosuggestion is fixed in the harvesting PR
