### ISSUE TITLE
accounts generated from seed do not match the mobile wallet

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#741]
I'm using the same seed, but the mobile wallet and desktop wallet create different sets of deterministic addresses. 

`worth organ swear soup weather regular tired focus social breeze timber ribbon among rough rude must nurse portion grow sight true wisdom fatigue front`

![image](https://user-images.githubusercontent.com/10395907/71063426-02040500-21b0-11ea-8d6c-8a135eaa3c32.png)

![image](https://user-images.githubusercontent.com/10395907/71063522-311a7680-21b0-11ea-8e26-6c40dcbf47d6.png)

I posted on the mobile wallet Github too. https://github.com/hatioin/nem-catapult-wallet/issues/233

**Comment by jabo38** [comment]
First address created by the desktop wallet is TDGCQE2HMDUJZCBPETS2MCI6D5PM36RHTE5YK3PU

First address created by the mobile wallet is TBPFGWYULMPOHXS4EFK2ZBHQBVG4GXSWNR7ODVFD

The expected behavior is to have mobile and desktop wallets creating the same account sets deterministically.

**Comment by decentraliser** [comment]
this is a known issue (#704),  it will be fixed by tomorrow
