### ISSUE TITLE
Mobile wallet can't read desktop invoices

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#742]
The mobile wallet can read mobile wallet invoices but not desktop invoices. Not sure where the problem is. 

Posted here too. https://github.com/hatioin/nem-catapult-wallet/issues/234

**Comment by decentraliser** [comment]
we use the standard invoice QR, I don't think it comes from us

**Comment by jabo38** [comment]
@decentraliser just to clarify, can you be a little more clear when you say "standard" what exactly does that mean and where can the source be matched?

**Comment by decentraliser** [comment]
I mean we use nem2-qr-code dedicated function for generating invoices

**Comment by decentraliser** [comment]
https://github.com/nemfoundation/nem2-desktop-wallet/blob/cc56735f1ee78576856ff3d493efc9a22cfbeb71/src/views/monitor/monitor-invoice/MonitorInvoiceTs.ts#L122

**Comment by decentraliser** [comment]
sent test cases and comments in the mobile slack channel

**Comment by decentraliser** [comment]
closing it, this should be fixed on the wallet side
