### ISSUE TITLE
entering private key on NIS1 testnet and Catapult testnet don't generate the same addresses

### ISSUE THREAD

**Issue by jabo38** [nemfoundation/nem2-desktop-wallet#746]
Private key example: C7D69A550806003DC0C0B6E2E5329E4760ACC01174DFB0C6C4005DA324522943

The address generated on NIS1: TD3BSH-B5F4PB-DIA42S-2CZSGI-ER4MH6-ZQT34L-WWMD

The address generated on Catapult: TDGCQE2HMDUJZCBPETS2MCI6D5PM36RHTE5YK3PU

Shouldn't these both be the same?

Catapult testnet public key: 429E5DDC45E525591EDE7953CCBB62EF16F0269B2926409FED84C355B51856FA

NIS1 public key: 9dbe7b6a60bba95390dd261493af9b4747324bdf0c7665c5ccfbe6f656a33578

So clearly the same private key is not making the same public keys.

**Comment by decentraliser** [comment]
@evias do you know why?

**Comment by domakun** [comment]
@evias We can not generate same public key between NIS1 and Catapult.

**Comment by jabo38** [comment]
![image](https://user-images.githubusercontent.com/10395907/71075360-43ec7580-21c7-11ea-96d3-6f37eaeb1ba0.png)

**Comment by jabo38** [comment]
@decentraliser for Catapult I'm using node http://api-harvest-20.ap-southeast-1.nemtech.network:3000

For the NIS1 testnet I'm using node http://hugetestalice.nem.ninja

**Comment by decentraliser** [comment]
@evias are the NIS1 and NEM2 keypairs compatible? Just tried with MAIN_NET and keys are different
