### ISSUE TITLE
Network default mosaic namespace setting

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#76]
Should be able to set the default network mosaic namespace, in networks settings
(to cover the case when a network's default mosaic is not nem.xem)

this might be confusing for regular users who will not come across custom networks, so might be a bit "hidden" in some way?

**Comment by evias** [comment]
Agree, can be something also under Settings screen.

**Comment by NemTechCN** [comment]
fixed
