### ISSUE TITLE
Bug and user experience improvement for Multisig Convert Page

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#82]
**Expected Behaviour**

The multi-signature account conversion screen, in terms of UI, should provide with a dropdown list of accounts that _can be converted_ to multi-signature (because they are stored in same account), and should add an item _custom private key_ to that dropdown in order to permit converting accounts outside the application account.

The dropdown list should filter out accounts that are already multi-signature accounts.

The fees part of the UI should be kept simple, with **one Lock fee** (or "Spam Protection Fee"), and **one Conversion Fee**. For both of them, a _fee recommendation_ should be provided to the user. 

_Transaction Fee Recommendations_ :

This can be done by calculating the size of the transaction (`Transaction.getSize()`) and multiplying by a pre-defined fee multiplier. 

For the first, the fee multiplier _can be set to 200_. This number will change with the definition of the testnet network.

**Actionable Items**

- Remove duplicate "Inner Fee" and replace by "Conversion Fee"
- Rename "Aggregate Fee" to "Spam Protection Fee" or "Lock Fee"
- Add a "Account to Convert" dropdown list on the top of the component to select account to convert
    * Linked to that dropdown, there should be a _read-only_ private key input appearing with the private key of selected account.
    * Add a "Custom Private Key" item to the dropdown list that will permit to input a custom private key (custom account to convert).
- Add fee recommendations with first version using pre-defined fee multiplier (200).

**Actual Behaviour**

There is an error when trying to convert an account to multi-signature as shown in below screenshot.

<img width="538" alt="Screenshot 2019-09-06 at 9 06 42 PM" src="https://user-images.githubusercontent.com/141805/64454113-68c24e80-d0ea-11e9-8395-65147b7516fb.png">

The settings defined for this transaction were: Min Approval=1 and Min Removal=1 with only 1 cosignatory public key added.

Also, I do not see that the private key is being added to the transaction and this is a little confusing to configure multi-signature accounts. On the top of the screen it should permit to select *which account must be converted* such that the end-user always knows which account is currently being configured to multi-signature.

**Comment by NemTechCN** [comment]
Do you mean we get innerTransaction fee by calculating the size of the transaction, and get bonded fee by another calculating ?

**Comment by NemTechCN** [comment]
fixed
