### ISSUE TITLE
UI: enable users clearing their cache if they lost their password

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#83]

**Comment by evias** [comment]
More specifically, on the **Lock Password** window. 

Also would like to question the actual setup here @NemTechCN @decentraliser : 

- Why is there 2 types of passwords? There is one that locks the complete app, and one that locks each wallet. 

- Why isn't the lock applied as a sort of login with wallet password?

The fact that there is 2 different types of passwords is going to introduce a lot of confusion and also may affect loss of keys.

**Comment by decentraliser** [comment]
There are 4 possibilities
-current: login with a main password (that will encrypt the PublicAccount
objects in the local storage for user privacy), and have multiple wallets
with multiple passwords available. This opens the possibilities of having
several login passwords, that have several wallets.
See here:
https://nem2.slack.com/archives/CME5PV744/p1566885975001100?thread_ts=1566885975.001100&cid=CME5PV744

- login with wallet password, and then you only have the wallet you logged
in with available in the session

- no main login, all public account objets are in plain text in the
localStorage

**Comment by evias** [comment]
closing this task due to definition of #87
