### ISSUE TITLE
Offline settings: missing reset to default button

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#830]
If data available from a node: default data = data from node
else, just use default data (empty values)

it is to cover the case when you have a valid network, and then you play with offline settings, and after you want to go back to the initial state

**Comment by domakun** [comment]
where do we get default data, previous node data?

**Comment by decentraliser** [comment]
Let me update the description
But let's wait for the answer to this: https://nem2.slack.com/archives/CME5PV744/p1578471207001800

**Comment by decentraliser** [comment]
offline settings have been removed until further discussion over the implementation of offline-signing feature
