### ISSUE TITLE
NEM2 Wallet "help" menu items lead to wrong projects

### ISSUE THREAD

**Issue by r3n3x** [nemfoundation/nem2-desktop-wallet#840]
V 0.8.11 / MacOS
<img width="808" alt="Screenshot 2020-01-12 at 19 17 55" src="https://user-images.githubusercontent.com/23291787/72217972-421c9480-3570-11ea-8eee-dcc88001d484.png">

The HELP menu items lead to these links:
https://electronjs.org
https://github.com/electron/electron/tree/v7.1.7/docs#readme
https://discuss.atom.io/c/electron
https://github.com/electron/electron/issues

Expected behavior: Links to NEM or SYMBOL websites, or NEMWALLET2 Github.

**Comment by dl-nice** [comment]
ok. i will fix
