### ISSUE TITLE
Bug in dashboard and multisig pages

### ISSUE THREAD

**Issue by domakun** [nemfoundation/nem2-desktop-wallet#846]
![image](https://user-images.githubusercontent.com/34330538/72231646-9dde3080-35f7-11ea-8af5-3d9bb98b1977.png)

**Comment by decentraliser** [comment]
all the numbers are going crazy here (note the 175 nodes on the screenshot)
I guess the lint should have broken something

**Comment by domakun** [comment]
it is a pointer bug in setInterval function, fixed it in pr #844

**Comment by domakun** [comment]
![image](https://user-images.githubusercontent.com/34330538/72236214-d76f6580-3610-11ea-9265-8ea54d7cb172.png)
