### ISSUE TITLE
node status bug

### ISSUE THREAD

**Issue by domakun** [nemfoundation/nem2-desktop-wallet#847]
![image](https://user-images.githubusercontent.com/34330538/72231763-32489300-35f8-11ea-9a5e-f66349f30fb7.png)
the node should be valid

**Comment by decentraliser** [comment]
not sure, this node might be experiencing issues
just experienced issues on the explorer

![image](https://user-images.githubusercontent.com/36499647/72232332-78ebbc80-35fb-11ea-8f4c-d38a3ad8c7dd.png)

**Comment by domakun** [comment]
can not reproduce after merger from master, will open when the error show again
