### ISSUE TITLE
Co-sign transaction does not reach bottom-level signer in multilevel multisig

### ISSUE THREAD

**Issue by trestoJP** [nemfoundation/nem2-desktop-wallet#851]
![multisig001](https://user-images.githubusercontent.com/59822825/72252526-c50e1f80-3642-11ea-8009-c0a8ba336601.png)

I set up this multilevel multisig configuration.
A sent a transaction to transfer mozaic from Red to B, but none of the bottom 9 signers have received the Co-sign transaction.

**Comment by trestoJP** [comment]
In this case, the nine co-signers cannot even request a withdrawal from the Red address. Doesn't multilevel multisig work from desktop wallet?

**Comment by decentraliser** [comment]
Multilevel is still an open issue, I'm currently working on it.
Will keep you posted!
