### ISSUE TITLE
Mosaic / Namespace creation broken for multisig accounts that have more than 1 cosigner

### ISSUE THREAD

**Issue by trestoJP** [nemfoundation/nem2-desktop-wallet#852]
To create a mosaic for a multisig account, the co-signer selected the multisig account and pressed the create button, but nothing happened.

**Comment by decentraliser** [comment]
Do you have more details? 
I just created a mosaic for a multisig account successfully
Are you sure that the cosignatory account had enough XEM to cover the transaction? If not, it would fail silently

**Comment by trestoJP** [comment]
![ 2020-01-13 21-05-02-235](https://user-images.githubusercontent.com/59822825/72254944-ccd0c280-3648-11ea-8bb0-b90f50de0b25.png)
When I enter password here and click "confirm", the window just disappears and nothing happens.
The account that wants to create a mosaic is [this #851](https://github.com/nemfoundation/nem2-desktop-wallet/issues/851) Red account. "A" try to make a mosaic on Red multisig account.

**Comment by decentraliser** [comment]
thanks for reporting, this bug occurs for 2-2 multisig accounts
