### ISSUE TITLE
Zero fee not available

### ISSUE THREAD

**Issue by kodty** [nemfoundation/nem2-desktop-wallet#857]
Only "slow", "normal" and "fast" are available, but there is no option to send a transaction with zero fee. Adding a "Custom" fee that allows 0 would be good.

**Comment by decentraliser** [comment]
Hi! Thanks for the suggestion!
However, 0 fees won't work, the transaction would not get accepted by a node

In the near future, users will have the possibility to change the values of the slow, normal and fast fees!
