### ISSUE TITLE
Transactions Listing Component rewrite

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#86]
**Expected Behaviour**

The transactions list should be **one transactions list** with all types of transactions together and should be **a component that accepts parameters to enable filtering**.

In terms of UI, you can agree on a coloring scheme as follows:

_Non-Aggregate Transactions_ :

- If the active wallet is *recipient* of the transaction , list _icon_ in **green**.
- If the active wallet is *issuer* of the transaction, list _icon_ in **orange**.
- If the active wallet is only *involved* in the transaction (cosignature), list _icon_ in **orange**.

_Aggregate Transactions_ :

In case of aggregate transaction, the wallet _should_ list the aggregate as **one transaction** on the transaction list, with a specific icon, and when the user clicks it, the details should be using components that are _also normally used to display each type of transaction_. An example:

- Alice is the active wallet 
- Alice creates a aggregate complete transaction with following embedded transactions: 1 NamespaceRegistrationTransaction, 1 MosaicDefinitionTransaction, 1 MosaicAliasTransaction, 1 TransferTransaction

When this transaction is announced to the network, the active wallet Alice should be notified in the transaction list with **one aggregate transaction** - _optionally could be "extended" to view embedded transactions_ - when it is clicked, the popup will be using components as _normal_, for embedded transactions such that there will be correct listing of details for each embedded transaction.

This requires that transaction meta data be extracted from those transaction type components into a "TransactionMeta" (deadline, fee, hash) type of component.

**Actionable Items**

- Extract Transaction List component from Dashboard
- Merge Transaction List + "Receipts" List
- Decide on Aggregate transaction display (whether it can be extended or only clicked)
- Define Single Component for each Transaction Type's Details (TransferBody, NamespaceRegistrationBody, MosaicDefinitionBody, etc..)
- Use Single Components **also** when transactions are embedded in aggregate.

**Actual Behaviour**

currently it is complicated to understand which transactions one account has initiated and which one are incoming, and also to understand _where_ transactions are listed. 

:warning: it is also currently most likely not possible to embed the transaction list in different modules.

**Comment by decentraliser** [comment]
Gonna start on this one but not do everything in one go. Here is my plan:
1: $store: `transactionlist = []` instead of `transactionlist = {transfers, others}`
2.: Refactor transaction formatting methods
3. Make an event system that refreshes mosaics and namespaces object when a related transaction is confirmed
4. Refactor modal component

I won't change the view in this one
