### ISSUE TITLE
Duration mosaics not listed

### ISSUE THREAD

**Issue by trestoJP** [nemfoundation/nem2-desktop-wallet#860]
Mosaics that have duration are listed as expired mosaics on the asset list in the left side of dashboard.

The duration mosaics I created are
12
21023999
2102400
and
Unlimited duration

Also the mosaic list page no longer shows any Unlimited duration / Duration / Expired mosaics.

![ 2020-01-15 14-28-42-925](https://user-images.githubusercontent.com/59822825/72407585-5c8a8400-37a3-11ea-9f6c-93eda99c2ee2.png)

**Comment by trestoJP** [comment]
This account has 15 types of mosaics.

**Comment by decentraliser** [comment]
Thanks for opening an issue!

I have never encountered this situation, it looks like the mosaic data is not available
Are you sure that the selected wallet (top-right corner) has mosaics?

If yes, is it happening all the time?

**Comment by trestoJP** [comment]
Any duration mosaic can be selected when I want to transfer.

![f8i24-aa863](https://user-images.githubusercontent.com/59822825/72413818-fe19d180-37b3-11ea-912f-8a6bd057d6d3.gif)

When I create a any duration type of mosaic with another account, it will be listed correctly. The account has only four types of mosaics.

**Comment by domakun** [comment]
Hi, @trestoJP , please tell me how to reproduce this error, and are you using v0.8.11?

**Comment by trestoJP** [comment]
Yes, I'm using v0.8.11.

I don't know how to reproduce this error. I received a lot of mosaics and just made mosaics in several settings(12 duration, 21023999 duration, 2102400 duration and Unlimited duration). This account has 19 mosaics now.

**Comment by decentraliser** [comment]
Might be due to a great number of mosaic, causing a network ban
can you please send me one of each mosaic to TBP63Y2GBGPWTBDTXP7VLGFGFPV235RSMSEEY2CC when you have a moment?

**Comment by trestoJP** [comment]
@decentraliser I sent you all mosaics. However, the next mosaics remains on the list but cannot be sent.

・Expired mosaic sent by others
4708C0323A128991

・Expired mosaics I created
3B2B3BBE56A89135
595BC0E6BA5BED5B
5132200ED3328A9A

・Mosaic sent by others(the amount is 0 now but still on the list of dashboard)
63968A4861D8BF9A

**Comment by decentraliser** [comment]
Thanks a lot! We will investigate this case!

**Comment by trestoJP** [comment]
additional information
This error is also unable to select the mosaic to bind.

![ 2020-01-16 17-07-49-862](https://user-images.githubusercontent.com/59822825/72505418-3d632380-3883-11ea-87f0-89ac5279e3f0.png)

**Comment by trestoJP** [comment]
@domakun I have sent you the private key of that account.
I tried importing it into another account and the same error was reproduced.

**Comment by domakun** [comment]
@trestoJP thank you! where do you send me the private key? I didn't find it in mailbox or slack! By the way.

**Comment by trestoJP** [comment]
Oops. I sent to wrong address.
I sent again. Please check 872672707@qq.com

**Comment by domakun** [comment]
@trestoJP Have sent you an email, please have a look.

**Comment by trestoJP** [comment]
@domakun  I have confirmed this problem that solved on 8.1.12 . Thank you very much.

(I can't open email attachments in my environment. sorry.)

**Comment by decentraliser** [comment]
super! thanks!
