### ISSUE TITLE
Account / Wallets management improvement

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#87]
**Added by** @decentraliser 
- Adding a wallet to the localStorage and the Store should be done at one place only, and once per wallet creation / modification. It should better be done as an `AppWallet` method
- Remove everything related to SET_HAS_WALLET
- Never show the derivation path to user
- Add an address just by clicking on an "add address" button, incrementing the derivation path in a standard way

**Expected Behaviour**

The application should permit to **create accounts** which are secured by a password. _One account_ can hold _many wallets_.  Account objects should be represented as follows:

| Field | Type | Description |
| --- | --- | --- |
| name | string | The name of this account. |
| password | Password | The password used for encrypting wallets in this account. |
| mnemonic | MnemonicPassPhrase | The mnemonic pass phrase for generating wallets for this account. |
| wallets | Wallet[] | The list of wallets created for this account. |

Wallets are stored **in** accounts and accounts define encryption password. One "Wallet" should be _only_ a combination of _Public Key_, _Private Key_, _Generation Hash_ and _Network Type_. The generation hash property will make sure that we can identify when the user switches to a wrong network (switching to node on different network..). Wallet objects should be represented as follows:

| Field | Type | Description |
| --- | --- | --- |
| name | string | (Optional) The name of this wallet. |
| publicKey | PublicKey | The public key of this wallet. |
| derivationPath | string | The derivation path of the child wallet (in case of HD wallet) |
| encryptedPrivateKey | EncryptedPayload | The encrypted private key of this wallet (**could** be optional for HD wallets because can be re-generated from mnemonic+path). |
| generationHash | string | The network generationHash for this wallet. (cross-network security) |
| networkType | NetworkType | The type of network for which this wallet can be used. |

In terms of UI, the user should be able to _login to an account_ from the start screen, also should be able to _import a mnemonic pass phrase_ from that start screen such that a corresponding account + default wallet will be imported and the user can then login. After being logged in, the user can then choose the _create wallets_ inside the account. Wallets can be _either of_ **private key wallets** OR **HD child wallets**. In case of private key wallets, the private key **must** be encrypted with the account password. In case of HD child wallet, it is possible to skip the storage of _private key_ because the derivation path is enough to re-generate child wallet private key.

**Actionable Items**

- Remove **"Lock Password"** screen ; Should be replace with "Account Login" screen with dropdown list of accounts + password for login.
- Change "Create Wallet" / "Import Wallet" screens as described above
- Change "Account" and "Wallet" storage mechanism and relational mapping.
- Hide
**Actual Behaviour**

Currently each wallet can have one password for encryption, augmenting the risk for people to lose their password.

Additionally,  the HD wallets capacity is currently not being leveraged because users must create multiple mnemonic pass phrases instead of being offered the opportunity to create child accounts.

**Comment by decentraliser** [comment]
$store.account.wallet should only be a pointer to $store.app.walletList, and not a full wallet object

1. DRY
2. There are nasty edge cases when starting an async call that will update the wallet object, and switch wallet around the moment of values from the async call are assigned to the active wallet through SET_WALLET

**Comment by decentraliser** [comment]
The display order of the wallets should be done according to a wallet property (eg. `wallet.walletDisplayIndex`) instead of the orders of the wallets in the wallets array.

**Comment by NemTechCN** [comment]
Wallet should be  encrypted with the wallet independentpassword.Account password is used for privacy protection.If an account is worried about losing keys, this account can choose to set same password .

**Comment by jabo38** [comment]
IMO it is best to have only one password in the whole app. I've used so many software wallets for so many blockchains and almost always the default is one password for everything. Download and test 10 random software wallets from any store, or suggested list, and almost all of them will be secured with one password. 

Even hardware wallets have only one password that works not just across many addresses on the same blockchain but across many blockchains. Also, we will be having hardware wallet integrations in this app, so we need to make a quasi-similar user flow whether they are using a hardware wallet or a local .wlt file.  It is a bit odd to have people do it one way with hardware wallets and another way with local .wlt files.

**Comment by NemTechCN** [comment]
fixed

**Comment by evias** [comment]
Amazing work on the 0.2.7 release for accounts&wallets :+1:

--

**Feedback from 0.2.7:**

- Issue 1: When clicking the `Create` button, the wallet should simply create a new address for the end-user (without asking network type, name and derivation path).

- Issue 2: When activating different account (clicking on one of the two buttons as shown in screenshot below), it should *not reorganize* the list. It should only change the color of the **selected** wallet to be orange and all others blue.

![image](https://user-images.githubusercontent.com/141805/65312541-03af3400-db93-11e9-87a6-02a6a9828c68.png)

- Issue 3: When I create a new wallet, it automatically switches to the _dashboard tab_ (which is fine), but the menu keeps "Wallet" item active, as displayed in following screenshot

<img width="436" alt="Screenshot 2019-09-20 at 10 45 02 AM" src="https://user-images.githubusercontent.com/141805/65312972-d3b46080-db93-11e9-938d-4803e069ca02.png">

**Comment by decentraliser** [comment]
default wallet = m/44'/43'/0'/0'/0'

**Comment by NemTechCN** [comment]
fixed
