### ISSUE TITLE
Cannot send XEM from cosigner

### ISSUE THREAD

**Issue by meyns** [nemfoundation/nem2-desktop-wallet#873]
In 0.8.12 a cosigner cannot send XEM owned by the multisig account, only XEM from its own account.
The message pops up as "this value is too big" but there are enough XEM next to "Asset"
![image](https://user-images.githubusercontent.com/6676974/72802116-52f19800-3c4b-11ea-98cd-6739ff7a91e0.png)

**Comment by decentraliser** [comment]
nice catch!
