### ISSUE TITLE
Easier way to sign a multisig transactions by cosigner

### ISSUE THREAD

**Issue by meyns** [nemfoundation/nem2-desktop-wallet#874]
Can you implement an easier way to cosign a transaction? At the moment you have to go to multisig settings and then co-sign transactions.
Maybe with a popup mentioning if you want to cosign a transaction.

**Comment by decentraliser** [comment]
thanks for the suggestion!

Currently, only the transactions where the main account has to cosign are updated automatically

For the children accounts, we will soon implement a routine that will be watching for new transactions to cosign.

Currently, they are just being checked on login, when switching wallets, and when opening the cosignature tab

**Comment by decentraliser** [comment]
closed in favour of #880
