### ISSUE TITLE
Dashboard is showing the fee of an aggregate_bonded transaction instead of the amount

### ISSUE THREAD

**Issue by meyns** [nemfoundation/nem2-desktop-wallet#875]
In the dashboard an aggregate_bonded transaction is showing the fee instead of the amount sent.
Also you could give more info instead of "aggregate_bonded" with the transaction. 
For example: multisig transfer or multisig adjustment or ...
You can also add the fee next to the amount (and leave amount empty if it is a multisig adjustment or an importance transfer)
In my opinion you could drop the nem.xem mosaic mentioning and only mention a mosaic if it is not the main currency

**Comment by decentraliser** [comment]
Thanks for your advice!

The transaction list is currently being reworked with that in mind

**Comment by decentraliser** [comment]
closed in favour of #879
