### ISSUE TITLE
Unable to paste address on full desktop app for macOS

### ISSUE THREAD

**Issue by kekkyojin** [nemfoundation/nem2-desktop-wallet#877]
The desktop version of NEM2 wallet doesn't allow to paste an address.

Steps to reproduce
-------------------
1. Copy a NEM address into the macOS clipboard, no matter if using the wallet provided feature
2. Go create a new transfer
3. Click on the address field
4. Use the usual clipboard keys to paste the address

What happens
--------------
No address is pasted into the field. Tried to paste into other unrelated fields with the same result.

What was expected
--------------------
The address contained on the operating system clipboard should appear now on the input field. Trying to call the contextual right mouse button to look for a Paste menu item is useless as it is not working app-wide.

Operating context
------------------
Desktop app version: 0.8.12
Operating system: macOS 10.15.2 es-ES

**Comment by dl-nice** [comment]
Thank you for your feedback. I have just fixed it. The next version will be used.
