### ISSUE TITLE
Dashboard "Receive" screen improvements

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#88]
The "Receive" tab on the dashboard should be improved such that users understand the "amount" part. 

Currently the end-user has to click "Set amount" to add an amount/mosaic + message, I think this form should be just above or below the QR Code such that it is clear that the content of the QR Code is an invoice.

This screen must also allow to attach different mosaics than the default mosaic. Probably best to limit the number of mosaics that can be attached through _invoice_ to one.

Also, the tab should be renamed **Invoice**.

**Comment by NemTechCN** [comment]
![image](https://user-images.githubusercontent.com/45383558/64522785-656ad500-d32d-11e9-9e64-8a4887d7f55e.png)
this is the design diagram ,the page seems not very clrear now. Maybe pop-up windows.
