### ISSUE TITLE
UI Improvement - Allow Mnemonic Phrase to be copied

### ISSUE THREAD

**Issue by swdee** [nemfoundation/nem2-desktop-wallet#881]
Using the WWW wallet in a Browser the UI could be improved during new wallet generation.  

At step 3 `Backup Mnemonic Phrase` it lists the 24 seed words.   It would be useful to be able to select and copy all words so they can be easily pasted into a Password vault/wallet.  Without the ability to highlight and copy makes it annoying.

**Comment by decentraliser** [comment]
Hi!

Thanks for the suggestions!

Currently, there is no plan to make an official web (WWW) of this wallet.

The idea about not being able to copy-paste the mnemonic passphrase at the account creation phase is to force the user to note it down, for safety purposes

Note that you can still copy-paste it from the wallet page
![image](https://user-images.githubusercontent.com/36499647/72876735-282e3f00-3d32-11ea-9b15-ce9eb08c56b8.png)

**Comment by swdee** [comment]
I wasn't asking about having an online wallet (WWW), rather I was meaning using the www.zip file from the release (HTML version) locally on my computer.

Being able to copy/paste the mnemonic after the process of creating the wallet is meaningless.

Other coins wallets allow for copy/pasting the mnemonic words which is actually better than trying to manually copy everything down which is prone to mistakes and getting the word order wrong.  

Further more other coins wallets number the order of the words which the NEM2 wallet is lacking which further increases the chance of a user making mistakes.

So with these points in mind, to close this ticket off totally misses the point of a UI improvement during the wallet creation phase. Software should be designed to make things easy, not more difficult, as your average person will be turned away with processes that require more effort.

**Comment by decentraliser** [comment]
Ok, I'll escalate your concerns!

**Comment by decentraliser** [comment]
@swdee we will propose WWW build in the future. Note that it is not recommended to use a wallet in a browser environment

After discussion with the team, we will enable copy-pasting the mnemonic during the onboarding

thanks a lot for your feedback!

**Comment by decentraliser** [comment]
@swdee the WWW build is available in www.zip archives here
https://github.com/nemfoundation/nem2-desktop-wallet/releases/tag/v0.8.13
