### ISSUE TITLE
Failure Core Insufficient Balance

### ISSUE THREAD

**Issue by meyns** [nemfoundation/nem2-desktop-wallet#885]
![image](https://user-images.githubusercontent.com/6676974/72925805-99cab500-3d53-11ea-9b6a-7e743d8e37ef.png)
Tried to send a multisig XEM and got this result. I clearly have enough balance to send, I tried a very small amount as well.
First it says "Operation is succesful" and then it says "Failure Cure Insufficient Balance"

**Comment by decentraliser** [comment]
Thanks for reporting!

As a note:
- "Operation is successful" means the transaction was properly crafted and announced to the network
 - "Failure Cure Insufficient Balance" errors come from the server after the sender's balance has been verified

I have not been able to reproduce this error...

- Are you using [the latest version (0.8.13)](https://github.com/nemfoundation/nem2-desktop-wallet/releases/tag/v0.8.13)?
- Are you sure that the multisig account itself has enough token?
- What is your environment?

**Comment by meyns** [comment]
I have installed 0.8.13, checked in "about"
I am initiating a transaction from a cosignature account (2of3). I am sending nem.xem from the main account. There are enough coins in the main account.
The program flashes "operation is successful" and 1 second after it "Failure core insufficient balance".
And nothing is sent, and nothing to see in "co-sign transactions"

**Comment by meyns** [comment]
Also the way my wallet is setup is this:
Seedwallet-1 is the master wallet where the nem.xem is on
Seedwallet-2, seedwallet-3 and seedwallet-4 are the cosignatures with a 2/3 scheme with 0.000xxx balance (the small residual balance was from testing)

**Comment by decentraliser** [comment]
Do you have enough in the main account to cover the hash lock transaction? It should be 10 XEM + transaction fee

**Comment by decentraliser** [comment]
Are you sure that your balance is sufficient to cover the transfer amount + the transaction fee?

This is the only way I can reproduce a similar behaviour

If you send mosaics from the main account, please make sure its address shows in "from' in the transaction confirmation modal. If not, there could be a bug about the account that is selected to initiate the transaction but that would be odd.

![image](https://user-images.githubusercontent.com/36499647/72985867-e54b9480-3e21-11ea-92d7-8cc5cf528a36.png)

**Comment by meyns** [comment]
Yes, I'm really sure I'm sending from the right account
1st screenshot is just before sending. I'm sending 10XEM as the cosigner from the main account which has 11000XEM on it.
![image](https://user-images.githubusercontent.com/6676974/72992315-d64ded80-3df3-11ea-9ee9-a915846009a9.png)
2nd screenshot is after clicking send
![image](https://user-images.githubusercontent.com/6676974/72992350-e665cd00-3df3-11ea-936a-64b6d1b53b42.png)
(BTW i would suggest putting the from and to address under each other, in my screen there are just a few characters on a new line)

**Comment by meyns** [comment]
Tried to go back to 0.8.11 where it worked, and same result

**Comment by decentraliser** [comment]
When a multisig account has more than 1 cosigner, the cosigner that initiates a multisig transactions must announce an `Aggregate bonded transaction` to the network. Then, the other cosigners will be able to cosign this transaction.

Aggregate bonded transactions have to be announced in a `Lock transaction`. It will lock 10 XYM from the cosigner until the aggregate transaction is cosigned or discarded. This is a tool to prevent spamming.

Thus, if you want to announce an aggregate bonded transaction, you must make sure the cosigner has a balance of 10XEM + transaction fee.

[https://nemtech.github.io/concepts/aggregate-transaction.html#aggregate-bonded](More details here: https://nemtech.github.io/concepts/aggregate-transaction.html#aggregate-bonded
)
