### ISSUE TITLE
Delegated harvesting

### ISSUE THREAD

**Issue by meyns** [nemfoundation/nem2-desktop-wallet#887]
I would suggest some alterations in the delegated harvesting part:

- Way too little information what is happening, and what you can do
- No indication of vested balance or balance needed for harvesting
- My account has got the delegated harvesting thing and has sent a delegated harvesting request. I have then transformed the account to multisig, and now only at Find a harvesting node has an x next to it. And I cant do anything anymore because "Multi-signature accounts cannot initiate transactions". And I do not know if a cosignature is adding a remote account link for itself or for the master account.

**Comment by decentraliser** [comment]
Harvesting UI is still being worked on, I'll make sure your concerns are considered!
Thanks

**Comment by decentraliser** [comment]
Closed in favour of #892

[Asked about your question about converting a linked account to a multisig on the Slack](https://nem2.slack.com/archives/CEZKUE4KB/p1579830001016400), will paste the answer here
