### ISSUE TITLE
Implement AccountLink in Dashboard Remote Tab

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#90]
**Expected Behaviour**

The "Remote" tab of the Dashboard should permit to link a remote account.

**Actual Behaviour**

The form states "operation successful" but the transaction never appears and the status keeps saying "Not yet open".

**Comment by NemTechCN** [comment]
![image](https://user-images.githubusercontent.com/45383558/64523814-b7acf580-d32f-11e9-8b77-955a2d74f5e2.png)
![image](https://user-images.githubusercontent.com/45383558/64523918-fb076400-d32f-11e9-970d-4e521d775c97.png)

the 'not_yet open' related to harvesting income , and is not complete.
we can get link info from linked/unlink.

**Comment by NemTechCN** [comment]
fixed
