### ISSUE TITLE
Bug: MosaicDefinitionTransactionForm component does not allow divisibility=0

### ISSUE THREAD

**Issue by evias** [nemfoundation/nem2-desktop-wallet#93]
**Expected Behaviour**

Mosaic definition transaction form should permit divisibility of x where `0 >= x <= 6`.

**Actual Behaviour**

As shows following screenshot, **divisibility 0** is not possible.

<img width="847" alt="Screenshot 2019-09-07 at 7 03 22 PM" src="https://user-images.githubusercontent.com/141805/64478400-3119dc00-d1a8-11e9-9c16-e2dc8c72f28c.png">

**Comment by NemTechCN** [comment]
fixed
